src/Entity/Account.php
<?php

namespace App\Entity;

use App\Repository\AccountRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AccountRepository::class)]
class Account
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'uuid')]
    private $accountId;

    #[ORM\Column(type: 'float', nullable: true)]
    private $money;

    #[ORM\Column(type: 'datetime')]
    private $dateCreation;

    #[ORM\Column(type: 'string', length: 255)]
    private $status;

    public function __toString(): string
    {
        return $this->getNomCompte();
    }

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'accounts')]
    private $userId;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom_compte;

    #[ORM\OneToMany(mappedBy: 'messageSender', targetEntity: Message::class)]
    private $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    #[ORM\Column(type: 'string', length: 255)]
    private $iban;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccountId(): ?string
    {
        return $this->accountId;
    }

    public function setAccountId(string $accountId): self
    {
        $this->accountId = $accountId;

        return $this;
    }

    public function getMoney(): ?float
    {
        return $this->money;
    }

    public function setMoney(?float $money): self
    {
        $this->money = $money;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getNomCompte(): ?string
    {
        return $this->nom_compte;
    }

    public function setNomCompte(string $nom_compte): self
    {
        $this->nom_compte = $nom_compte;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setMessageSender($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getMessageSender() === $this) {
                $message->setMessageSender(null);
            }
        }
        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }
}

src/Controller/AccountsController.php
<?php

namespace App\Controller;

use App\Entity\Account;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

class AccountsController extends AbstractController
{
    #[Route('/accounts', name: 'accounts')]
    public function index(ManagerRegistry $doctrine, UserInterface $user): Response
    {

        return $this->render('accounts/index.html.twig', [
            'accountList' => $user->getAccounts(),
        ]);
    }

    #[Route('/accounts/{accountId}', name: 'accountsSingle')]

    public function singleAccount(ManagerRegistry $doctrine, $accountId, UserInterface $user): Response
    {

        $uuid = Uuid::fromString($accountId);
        $accountSingle = $doctrine->getRepository(Account::class)->findOneBy(['accountId' => $uuid]);
        if($accountSingle->GetUserId()->getId() != $user->getId()){
            return $this->redirectToRoute('accounts');
        }

        return $this->render('accounts/single.html.twig', [
            "account" => $accountSingle
        ]);
    }
}

templates/accounts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lydiot | Vos comptes{% endblock %}

{% block body %}
    <section class="accounts" style="margin: 1em auto; max-width: 800px;">
        <div class="wrapper-section"  >
            {% for message in app.flashes('success') %}
                <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md" role="alert">
                    <div class="flex">
                        <div>
                            <p class="font-bold">{{ message }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <h1>Les comptes de {{ app.user.surname }}  </h1>

            <ul>

                <li class="add-account"><a href="{{ path('create_account') }}"><span class="material-icons">add</span>Ajouter un compte</a></li>
                {% for account in accountList %}
                    {% if account.status != "archive" %}

                    <li class="accounts">
                        <a href="{{ path('accountsSingle', {accountId: account.accountId}) }}">
                            <bdi class="montant">{{account.money}}<span class="devise">€</span></bdi>
                            <span class="nom-compte">{{ account.nomCompte|capitalize }}</span>
                        </a>
                    </li>

                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </section>

{% endblock %}

templates/accounts/single.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lydiot | {{ account.nomCompte }}{% endblock %}

{% block body %}
    <section class="heading" style="margin: 1em auto; max-width: 800px;">
        <div class="wrapper-section mb-[4rem]" >
            {% for message in app.flashes('success') %}
                <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md" role="alert">
                    <div class="flex">
                        <div>
                            <p class="font-bold">{{ message }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <h1> Compte : {{ account.nomCompte }}</h1>
             <bdi> Montant : {{ account.money }}<span class="devise">€</span></bdi>
            <span>IBAN : {{ account.iban }}</span>
        </div>
    </section>
    <section class="single-accounts mb-[4rem]" style="margin: 1em auto; max-width: 800px;">
        <div class="wrapper-section">
            <div class="liens">
                <a href="{{ path('virement-account', {accountId: account.accountId}) }}"><span class="material-icons">account_balance_wallet</span>Ajouter de l'argent</a>
                <a href="{{ path('transaction-account', {accountId: account.accountId}) }}"><span class="material-icons">currency_exchange</span>Faire une transaction</a>
                <a href="{{ path('archive-account', {accountId: account.accountId}) }}"><span class="material-icons">delete</span>Supprimer le compte</a>
                <a href="{{ path('demande', {accountId: account.accountId}) }}"><span class="material-icons">account_balance_wallet</span>Demande de virement</a>
            </div>
        </div>
    </section>
{% endblock %}